### PR TITLE
Peripherial mode

### PR DESCRIPTION
**Pull request by jscrump59**
Added the remaining peripheral commands by sub-classing Bluetooth and changing the plugin variable's scope to protected. Created an extended demo program that exercises all of the functions with asynchronous responses on all applicable commands using the set of response codes. The callback launched from the initPeripheral command registers connects and disconnects.

I added a couple of helper classes to make creating a service easier.

### CODE REVIEW

**Comment by chen-fishbein** [comment]
Hi,
Thanks, it seems like you added the files to the root of the project.
Git treats them as new files which makes the diff unusable.
You need to change the files from their location and then push.
Let me know if you managed

**Comment by jscrump59** [comment]
Chen, 
Take a look to see if I got the changes to upload properly.
Jeff

**Review by jscrump59 — COMMENTED** [review]
Completed the implementation of remaining BTLE functions. Added a couple of helper methods to make creating services easier.

**Comment by jscrump59** [comment]
Chen,
I'm still not convinced that I've done this properly.
Jeff

**Comment by chen-fishbein** [comment]
I would suggest to try from scratch, fork the project add your changes and then open the pull request

**Pull request closed without merging**
